### ISSUE TITLE
Does not run PowerToys Run or block windows search.

### ISSUE THREAD

**Issue by HokoraYinphineMPP** [Illustar0/PowerToysRunEnhance#5]
Running Windows 10 Pro (22H2)
using v0.0.4

used inspector.exe to find program name

![Image](https://github.com/user-attachments/assets/045103db-44f4-4aaf-861e-d599fbd22b44)

tried: `検索`, `検索ボックス`, and `Search` for searchWindowName
tried: various shortcuts for powerToysRunHotKey

ran as standard and admin

config.toml
```toml
[settings]
searchWindowName = "検索ボックス"
powerToysRunHotKey = "ctrl+shift+`"
autoFocus = true
```

Win key does not block search or open PowerToys Run.
Program behaves as if it does nothing except open a taskbar icon.

![Image](https://github.com/user-attachments/assets/892b9f89-e13e-42dc-b8d9-d17b6308aac8)
